abbr -a dcb 'docker-compose build'
abbr -a dce 'docker-compose exec'
abbr -a dcps 'docker-compose ps'
abbr -a dcrestart 'docker-compose restart'
abbr -a dcrm 'docker-compose rm'
abbr -a dcr 'docker-compose run'
abbr -a dcstop 'docker-compose stop'
abbr -a dcup 'docker-compose up'
abbr -a dcupd 'docker-compose up -d'
abbr -a dcdn 'docker-compose down'
abbr -a dcl 'docker-compose logs'
abbr -a dclf 'docker-compose logs -f'
abbr -a dcpull 'docker-compose pull'
abbr -a dcstart 'docker-compose start'
abbr -a dck 'docker-compose kill'
